# Use a Node.js base image
FROM node:22 AS builder

# Set the working directory
WORKDIR /app

# Copy application files (if there are any, otherwise this step can be skipped)
COPY . .

# Install Angular CLI
RUN npm install -g @angular/cli@19
