# Use a Node.js base image
FROM node:22 AS builder

# Set the working directory
WORKDIR /app

# Copy application files (if there are any, otherwise this step can be skipped)
COPY . .

# Install Angular CLI
RUN npm install -g @angular/cli@19

#Copy package.json file
COPY package*.json ./

# Install npm
RUN npm install

# Start the Angular development server
CMD ["ng", "serve", "--host", "0.0.0.0"]
